---
title: "main"
output: html_document
---

```{r}

# Código original - Professor Raul
source("EntropyEstimationParetoKernel.R")
```

```{r}

set.seed(40028922)
```

```{r}

# gl_values_list: graus de liberdade pra testar
# uma lista
# gl = c(1, 2, 3, 4, 5, 10, 15, 20, 50, 100)

# sim_size: quantidade de replicações na simulação de monte carlo
# no artigo original foi feito 500

# limite superior no param h
# estava usando 50 

# sample_size: quantidade de amostras (no artigo feito para 30, 60, 200, 500)

sim_monte_carlo <- function(gl_values, sim_size, lim_sup, sample_size){
  
  df_results <- data.frame(
    type = character(),
    variance = numeric(),
    bias = numeric(),
    mse = numeric(),
    gl = numeric()
  )
  
  methods <- c("Gaussian", "Laplace", "Cauchy", "Pareto", "NND", "SS")
  
  for (gl in gl_values){

    sim_results <- matrix(NA_real_, nrow = sim_size, ncol = length(methods))
    
    # distribuição real
    H.true <- 0.5*(gl+1)*(digamma((gl+1)/2)-digamma(gl/2))+log(sqrt(gl)*beta(gl/2,0.5))
    
    print("Fazendo simulação de Monte Carlo")
    print("Graus de Liberdade")
    print(gl)
    print("----------------------------------")
        
    for (b in seq_len(sim_size)) {
    
      # t de student, tamanho "n.size" com "gl" graus de liberdade
      # logico, univariado
      # (um arrayzão lindo)
      x.sim <- rt(sample_size, df = gl)
  
      h.G.sim <- optimize(function(h) Entropy.G(x.var = x.sim, h = h), lower = 0, upper = lim_sup)
      h.C.sim <- optimize(function(h) Entropy.C(x.var = x.sim, h = h), lower = 0, upper = lim_sup)
      h.L.sim <- optimize(function(h) Entropy.L(x.var = x.sim, h = h), lower = 0, upper = lim_sup)
      h.P.sim <- optim(par = c(0.5, 1), fn = function(par) Entropy.P(x.var = x.sim, par = par))
  
      sim_results[b, ] <- c(
        h.G.sim$objective,
        h.L.sim$objective,
        h.C.sim$objective,
        h.P.sim$value,
        H.NND(x.sim),
        H.SSM(x.sim)
      )
    }
      
    
    # pego os resultados e faço um dataframe com MSE, Variância e Bias
    errors <- sim_results - H.true
  
    df_atual <- data.frame(
      type = methods,
      variance = apply(sim_results, 2, var),
      bias = colMeans(errors),
      mse = colMeans(errors^2),
      gl = gl
    )
    
    # boto esse resultado no dataframe final com os outros gls
    df_results <- rbind(df_results, df_atual)
  }
  
  return(df_results)
  
}

```

```{r}

gl_list = c(1, 2, 3, 4, 5, 10, 15, 20, 50, 100)

start <- Sys.time()

df_sample_size_30 <- sim_monte_carlo(gl_values = gl_list, sim_size = 500, lim_sup = 50, sample_size = 30)

end <- Sys.time()

duracao <- end - start

print("Tempo da simulação")
print(duracao)
```

```{r}

write.csv(df_sample_size_30, "df_sample_size_30.csv", row.names = FALSE)

```

```{r}

start <- Sys.time()

df_sample_size_60 <- sim_monte_carlo(gl_values = gl_list, sim_size = 500, lim_sup = 50, sample_size = 60)

end <- Sys.time()

duracao <- end - start

print("Tempo da simulação")
print(duracao)
```

```{r}

write.csv(df_sample_size_60, "df_sample_size_60.csv", row.names = FALSE)
```

```{r}

start <- Sys.time()

df_sample_size_200 <- sim_monte_carlo(gl_values = gl_list, sim_size = 500, lim_sup = 50, sample_size = 200)

end <- Sys.time()

duracao <- end - start

print("Tempo da simulação")
print(duracao)
```

```{r}

write.csv(df_sample_size_200, "df_sample_size_200.csv", row.names = FALSE)
```

```{r}

start <- Sys.time()

df_sample_size_500 <- sim_monte_carlo(gl_values = gl_list, sim_size = 500, lim_sup = 50, sample_size = 500)

end <- Sys.time()

duracao <- end - start

print("Tempo da simulação")
print(duracao)
```

```{r}

write.csv(df_sample_size_500, "df_sample_size_500.csv", row.names = FALSE)
```
